# Default PII Detection Rules for MkDocs Material Prep
# This file defines patterns and rules for detecting and removing
# personally identifiable information from markdown files.

# Regular expression patterns for detecting PII in content
pii_patterns:
  # Email addresses
  email: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
  
  # Phone numbers (US format with optional separators)
  phone: '\b(?:\+?1[-.\s]?)?\(?[0-9]{3}\)?[-.\s]?[0-9]{3}[-.\s]?[0-9]{4}\b'
  
  # Social Security Numbers (XXX-XX-XXXX format)
  ssn: '\b\d{3}-\d{2}-\d{4}\b'
  
  # Credit card numbers (basic pattern)
  credit_card: '\b(?:\d{4}[-\s]?){3}\d{4}\b'
  
  # IP addresses
  ip_address: '\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b'
  
  # Common personal identifiers in text
  personal_id: '\b(?:employee\s+id|emp\s+id|badge\s+#?|id\s+#?)\s*:?\s*[A-Z0-9]{3,}\b'

# Frontmatter fields to remove from YAML headers
frontmatter_remove:
  - author
  - authors
  - contact
  - email
  - created_by
  - last_modified_by
  - owner
  - maintainer
  - reviewer
  - approver
  - employee_id
  - badge_number
  - internal_id
  - personal_notes
  - private_comments
  - draft_notes

# Substitution patterns for specific replacements
substitutions:
  # Default contact email to use when replacing personal emails
  default_contact: "contact@example.com"
  
  # Default author name for attribution
  default_author: "Documentation Team"
  
  # Generic department reference
  default_department: "Support Team"

# Additional MkDocs Material specific fields that might contain PII
mkdocs_material_fields:
  # Navigation and metadata fields that might contain personal info
  - nav_exclude_reason
  - internal_notes
  - review_status
  - assigned_to
  - created_by_user
  - last_editor
  
# Content patterns that should be completely removed (not just redacted)
remove_patterns:
  # Internal comments or notes
  internal_comment: '<!--\s*INTERNAL:.*?-->'
  
  # Draft markers
  draft_marker: '<!--\s*DRAFT.*?-->'
  
  # TODO items with personal assignments
  personal_todo: '<!--\s*TODO\s*\([^)]*@[^)]*\):.*?-->'

# Patterns for content that should be replaced with generic alternatives
replace_patterns:
  # Replace "Contact John Doe at john@company.com" with generic version
  contact_person: 
    pattern: 'Contact\s+[A-Z][a-z]+\s+[A-Z][a-z]+\s+at\s+[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}'
    replacement: 'Contact our support team at contact@example.com'
  
  # Replace "Created by FirstName LastName" with generic
  created_by_name:
    pattern: 'Created\s+by\s+[A-Z][a-z]+\s+[A-Z][a-z]+'
    replacement: 'Created by the documentation team'
